# This file shows the default configuration of Meilisearch.
# All variables are defined here: https://www.meilisearch.com/docs/learn/configuration/instance_options#environment-variables

# Designates the location where database files will be created and retrieved.
db_path = "data.ms/"

# Configures the instance's environment. Value must be either `production` or `development`.
env = "development"

# The address on which the HTTP server will listen.
http_addr = "localhost:7700"

# Sets the instance's master key, automatically protecting all routes except GET /health.
master_key = "eSampleMasterKey"

# Deactivates Meilisearch's built-in telemetry when provided.
# Meilisearch automatically collects data from all instances that do not opt out using this flag.
# All gathered data is used solely for the purpose of improving Meilisearch, and can be deleted at any time.
# no_analytics = true

# Sets the maximum size of accepted payloads.
http_payload_size_limit = "100 MB"

# Defines how much detail should be present in Meilisearch's logs.
# Meilisearch currently supports six log levels, listed in order of increasing verbosity:  `OFF`, `ERROR`, `WARN`, `INFO`, `DEBUG`, `TRACE`
log_level = "INFO"

# Sets the maximum amount of RAM Meilisearch can use when indexing.
# max_indexing_memory = "2 GiB"

# Sets the maximum number of threads Meilisearch can use during indexing.
# max_indexing_threads = 4


#############
### DUMPS ###
#############

# Sets the directory where Meilisearch will create dump files.
dump_dir = "dumps/"

# Imports the dump file located at the specified path. Path must point to a .dump file.
# import_dump = "./path/to/my/file.dump"

# Prevents Meilisearch from throwing an error when `import_dump` does not point to a valid dump file.
ignore_missing_dump = false

# Prevents a Meilisearch instance with an existing database from throwing an error when using `import_dump`.
ignore_dump_if_db_exists = false


#################
### SNAPSHOTS ###
#################

# Enables scheduled snapshots when true, disable when false (the default).
# If the value is given as an integer, then enables the scheduled snapshot with the passed value as the interval
# between each snapshot, in seconds.
schedule_snapshot = false

# Sets the directory where Meilisearch will store snapshots.
snapshot_dir = "snapshots/"

# Launches Meilisearch after importing a previously-generated snapshot at the given filepath.
# import_snapshot = "./path/to/my/snapshot"

# Prevents a Meilisearch instance from throwing an error when `import_snapshot` does not point to a valid snapshot file.
ignore_missing_snapshot = false

# Prevents a Meilisearch instance with an existing database from throwing an error when using `import_snapshot`.
ignore_snapshot_if_db_exists = false


###########
### SSL ###
###########

# Enables client authentication in the specified path.
# ssl_auth_path = "./path/to/root"

# Sets the server's SSL certificates.
# ssl_cert_path = "./path/to/certfile"

# Sets the server's SSL key files.
# ssl_key_path = "./path/to/private-key"

# Sets the server's OCSP file.
# ssl_ocsp_path = "./path/to/ocsp-file"

# Makes SSL authentication mandatory.
ssl_require_auth = false

# Activates SSL session resumption.
ssl_resumption = false

# Activates SSL tickets.
ssl_tickets = false


#############################
### Experimental features ###
#############################

# Experimental metrics feature. For more information, see: <https://github.com/meilisearch/meilisearch/discussions/3518>
# Enables the Prometheus metrics on the `GET /metrics` endpoint.
experimental_enable_metrics = false

# Experimental RAM reduction during indexing, do not use in production, see: <https://github.com/meilisearch/product/discussions/652>
experimental_reduce_indexing_memory_usage = false

# Experimentally reduces the maximum number of tasks that will be processed at once, see: <https://github.com/orgs/meilisearch/discussions/713>
# experimental_max_number_of_batched_tasks = 100
