version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      MEILI_CONFIG_FILE_PATH: "/meili_data/config.toml"
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data
      - ./config.toml:/meili_data/config.toml

volumes:
  postgres_data:
  meili_data:
