[package]
name = "actix-diesel-postgres"
version = "0.1.0"
authors = ["my <sosnsg@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.12"
actix-web = "4"
diesel = { version = "2.0.0", features = ["postgres", "r2d2"] }
dotenv = "0.15.0"
serde = { version = "1.0", features = ["derive"] }
env_logger = "0.9"
log = "0.4"
