---
route:
  - id: something
    scheme: http
    authority:
      host: 127.0.0.1
      port: 8001
    path: /something
  - id: product
    scheme: http
    authority:
      host: 127.0.0.1
      port: 8001
    path: /product
  - id: default
    scheme: http
    authority:
      host: 127.0.0.1
      port: 8001
    path: /
